<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings> 
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <Target Name="PostBuildCopy" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\..\Unity\Assets\Plugins" />
    <Copy 
      SourceFiles="$(TargetDir)$(TargetName).dll"
      DestinationFiles="$(MSBuildProjectDirectory)\..\Unity\Assets\Plugins\$(TargetName).dll"
      SkipUnchangedFiles="true" />
  </Target>

</Project>
