<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simulation\Simulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SharedAssets\TestMaps\**\*">
      <Link>TestMaps\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <TargetPath>TestMaps\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
