name: .NET

on:
  push:
    branches: [ "main", "pipeline-testing" ]
  pull_request:
    branches: [ "main", "pipeline-testing" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
      	submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore 
      run: |
        dotnet restore GameLogic/GameLogic.csproj
        dotnet restore GameLogicSimulation/GameLogicSimulation.csproj

    - name: Build
      run: |
        dotnet build GameLogic/GameLogic.csproj --no-restore --configuration Release
        dotnet build GameLogicSimulation/GameLogicSimulation.csproj --no-restore --configuration Release

    - name: Test
      run: |
        dotnet test GameLogic/GameLogic.csproj --no-build --configuration Release
        dotnet test GameLogicSimulation/GameLogicSimulation.csproj --no-build --configuration Release